name: firebasegetx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^2.0.0
  firebase_core: 1.3.0
  get: 4.1.4
  flutter_login: ^2.1.0
  lottie: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
    # - assets/
    - assets/lottie/login.json
